### PR TITLE
Fetch and show the latest version for GitLab repositories

### LINKED ISSUE #7417: Fetch and show the latest version of a project hosted on GitLab
### Context

Hi! 👋 

I'm documenting a Python package hosted on GitLab and, similar to a project hosted on GitHub, I would like to include the latest released version along with the rest of the repo information (e.g., stars) next to the search bar/as part of the main navigation drawer.

### Description

Similar to GitHub, GitLab also has an [API endpoint](https://docs.gitlab.com/ee/api/releases/#get-the-latest-release) to obtain information about the latest release. Thus, the following snippet 

https://github.com/squidfunk/mkdocs-material/blob/a5438a6dc23396023bbe9d73592fccd562ee4174/src/templates/assets/javascripts/components/source/facts/gitlab/index.ts#L48-L61

could be adapted based on the GitHub one,

https://github.com/squidfunk/mkdocs-material/blob/a5438a6dc23396023bbe9d73592fccd562ee4174/src/templates/assets/javascripts/components/source/facts/github/index.ts#L60-L75

in order to obtain the desired information.

You can see an example response using the following command (the relevant field is the `tag_name` one):

```bash
curl -L "https://gitlab.com/api/v4/projects/joaommpalmeiro%2Fgaveta/releases/permalink/latest"
```

The [list releases](https://docs.gitlab.com/ee/api/releases/#list-releases) API endpoint can also be used for this purpose.

Let me know what you think and if I can open a PR. Thanks!

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
- https://docs.gitlab.com/ee/api/releases/#get-the-latest-release

### Use Cases

Projects hosted on GitLab will also be able to show the latest version information. Additionally, repository information will become consistent, as we will be able to get the same information for GitHub and GitLab.

### Visuals

_No response_

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

### PR DESCRIPTION
**Pull request by joaopalmeiro**
Closes #7417 

## Testing

Adapt the `mkdocs.yml` file with the following repositories:

### Without releases

```yaml
# Repository
repo_name: dreamer-labs/libraries/jinja2-ansible-filters
repo_url: https://gitlab.com/dreamer-labs/libraries/jinja2-ansible-filters
```

Screenshot 2024-08-03 at 15 34 05

### With releases

```yaml
# Repository
repo_name: gitlab-org/gitlab
repo_url: https://gitlab.com/gitlab-org/gitlab
```

Screenshot 2024-08-03 at 15 38 52

```yaml
# Repository
repo_name: alelec/gitlab-release
repo_url: https://gitlab.com/alelec/gitlab-release
```

Screenshot 2024-08-03 at 15 40 08

```yaml
# Repository
repo_name: joaommpalmeiro/gaveta
repo_url: https://gitlab.com/joaommpalmeiro/gaveta
```

Screenshot 2024-08-03 at 15 43 29

### CODE REVIEW

**Comment by joaopalmeiro** [comment]
Hi, @squidfunk!

PR is ready for review. Let me know your feedback please.

File: src/templates/assets/javascripts/components/source/facts/gitlab/index.ts [hunk 1]
```diff
@@ -49,13 +61,30 @@ export function fetchSourceFactsFromGitLab(
   base: string, project: string
 ): Observable<SourceFacts> {
   const url = `https://${base}/api/v4/projects/${encodeURIComponent(project)}`
-  return requestJSON<ProjectSchema>(url)
+  return zip(
+
+    /* Fetch version */
+    requestJSON<Release>(`${url}/releases/permalink/latest`)
```
Comment (squidfunk) [inline src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: Does this also work with privately hosted GitLab? Or does it only work on GitLab's Cloud offering?

**Review by squidfunk — APPROVED** [review]
Looking good, thanks! Just a comment/question ⬆️

File: src/templates/assets/javascripts/components/source/facts/gitlab/index.ts (hunk 1 above)
Comment (joaopalmeiro) [reply src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: With the current implementation, I would say no because those repositories are typically _private_, not public. However, the [API endpoint](https://docs.gitlab.com/ee/api/releases/) used is the same:

```
Tier: Free, Premium, Ultimate
Offering: GitLab.com, Self-managed, GitLab Dedicated
```

Comment (squidfunk) [reply src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: Okay, we need to test if the additions break the stars/forks code, when run in a private installation. It's fine if the release isn't shown, but at least the stars should work. How can we ensure this?

Comment (joaopalmeiro) [reply src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: To complement my previous answer, the regular expression to detect whether a URL is from GitLab is not enough to cover all possible self-hosted GitLab instances. I also know [Framagit](https://framagit.org/explore) (by [Framasoft](https://framasoft.org/en/)) and the regular expression doesn't match:

https://github.com/squidfunk/mkdocs-material/blob/a5438a6dc23396023bbe9d73592fccd562ee4174/src/templates/assets/javascripts/components/source/facts/_/index.ts#L79-L80

However, the GitLab API endpoints work:

```bash
curl -L https:/framagit.org/api/v4/projects/framasoft%2Fmobilizon/releases/permalink/latest
```

I'm not sure how to resolve this (List of self-hosted GitLab instances to try to match a URL? API request?), so I'd say we can discuss it in another issue if you agree.

Comment (squidfunk) [reply src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: Thanks for taking the time to clarify! I think my question was phrased a bit badly talking about privately hosted GitLab, where I just meant self-hosted. Of course this can't work with private repositories, it's the same for GitHub, so all good!

> To complement my previous answer, the regular expression to detect whether a URL is from GitLab is not enough to cover all possible self-hosted GitLab instances. 

Yes, we're aware of that, but we're currently not considering making configuration even more complicated. If works for the majority of cases, and otherwise can be forked and adjusted. This has been asked before. Since MkDocs is undergoing a [rewrite](https://github.com/mkdocs/sketch), we're currently not considering changing anything on the source functionality, since it is completely unclear how this functionality will be supported in the future. We'll do our absolute best to keep this feature, of course.

Comment (squidfunk) [reply src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: Forgot to say: this is good to merge then!

Comment (joaopalmeiro) [reply src/templates/assets/javascripts/components/source/facts/gitlab/index.ts:67]: Thanks a lot, @squidfunk!
